export type TabName =
  | "Home"
  | "Tasks"
  | "Site"
  | "AdminDashboard"
  | "Projects"
  | "Approvals"
  | "AdminTasks"
  | "AdminOrders"
  | "AdminDeliveries"
  | "AdminSetup"
  | "VendorHome"
  | "Orders"
  | "Deliveries"
  | "More";

export type SheetName =
  | "notifications"
  | "report"
  | "material"
  | "expense"
  | "attendance"
  | "issue"
  | "profile"
  | "settings"
  | "progress"
  | "cash"
  | "messages"
  | "documents"
  | "activity"
  | null;
