import { StyleSheet } from "react-native";
import { colors, radius } from "../../theme";

export const sheetStyles = StyleSheet.create({
  modal: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(12,24,20,.42)",
  },
  sheet: {
    height: "91%",
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
  },
  handle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.border,
    alignSelf: "center",
    marginTop: 10,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: { color: colors.ink, fontSize: 21, fontWeight: "800", maxWidth: 270 },
  subtitle: { color: colors.inkMuted, fontSize: 11, marginTop: 3 },
  form: { padding: 20, paddingTop: 2, gap: 15, paddingBottom: 12 },
  taskSelection: { gap: 8 },
  taskChoice: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  taskChoiceActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  taskChoiceCopy: { flex: 1 },
  taskChoiceTitle: { color: colors.ink, fontSize: 11, fontWeight: "700" },
  taskChoiceMeta: { color: colors.inkMuted, fontSize: 9, marginTop: 3 },
  reportHistory: { gap: 10, marginTop: 8 },
  reportListHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  reportListCount: { color: colors.inkMuted, fontSize: 10, marginTop: 4 },
  reportFilters: { flexDirection: "row", gap: 8 },
  reportFilter: { flex: 1 },
  reportCard: { padding: 14, gap: 8 },
  reportCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  reportWork: { color: colors.ink, fontSize: 11, lineHeight: 17 },
  reportMeta: { color: colors.inkMuted, fontSize: 9 },
  sheetTabs: {
    flexDirection: "row",
    padding: 4,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
  },
  sheetTab: {
    flex: 1,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
  },
  sheetTabActive: { backgroundColor: colors.surface },
  sheetTabText: { color: colors.inkMuted, fontSize: 11, fontWeight: "700" },
  sheetTabTextActive: { color: colors.primary },
  splitFields: { flexDirection: "row", gap: 10 },
  splitField: { flex: 1, gap: 7 },
  attendanceHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.primarySoft,
  },
  attendanceHintText: {
    flex: 1,
    color: colors.primary,
    fontSize: 10,
    lineHeight: 15,
  },
  attendanceCard: { padding: 14, gap: 12 },
  attendanceCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  attendanceFields: {
    gap: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  attendanceSummaryRow: { flexDirection: "row", gap: 8 },
  attendanceCountCard: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  attendanceCountValue: { color: colors.ink, fontSize: 18, fontWeight: "800" },
  attendanceCountLabel: { color: colors.inkMuted, fontSize: 9, marginTop: 3 },
  attendanceHistoryCard: { padding: 14, gap: 8 },
  attendanceHistoryMeta: { color: colors.inkMuted, fontSize: 10 },
  financeCard: { padding: 14, gap: 8 },
  financeAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  financeAmount: { color: colors.ink, fontSize: 18, fontWeight: "800" },
  receiptPreview: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 10,
    backgroundColor: colors.primarySoft,
  },
  receiptName: {
    flex: 1,
    color: colors.primary,
    fontSize: 10,
    fontWeight: "700",
  },
  cashReturnCard: { padding: 14, gap: 12 },
  issueCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  issueAttachment: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  issueAttachmentName: { flex: 1, color: colors.ink, fontSize: 10 },
  issueHistoryCard: { padding: 12, gap: 7 },
  communicationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  notificationCard: {
    padding: 13,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
  },
  notificationCardUnread: { borderColor: colors.primary },
  notificationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  conversationCard: {
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  conversationPreview: { color: colors.ink, fontSize: 10, marginTop: 6 },
  messageBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  messageBadgeText: { color: colors.white, fontSize: 9, fontWeight: "800" },
  conversationTopbar: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 9,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  conversationIdentity: { gap: 2 },
  messageSender: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: "800",
    marginBottom: 4,
  },
  messageAttachment: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 7,
  },
  messageAttachmentText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: "700",
  },
  pendingAttachment: {
    marginHorizontal: 12,
    padding: 9,
    borderRadius: 10,
    backgroundColor: colors.primarySoft,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  documentUploadCard: { gap: 12 },
  documentDetailCard: { padding: 18, alignItems: "center", gap: 5 },
  documentPreviewIcon: {
    width: 82,
    height: 82,
    borderRadius: 24,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  documentDetailName: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: "800",
    textAlign: "center",
  },
  documentInfoList: { width: "100%", gap: 13, marginTop: 15 },
  documentActions: { flexDirection: "row", gap: 10 },
  documentSecondaryAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  documentPrimaryAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  documentSecondaryActionText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800",
  },
  documentPrimaryActionText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  documentEmpty: {
    color: colors.inkMuted,
    fontSize: 10,
    textAlign: "center",
    padding: 22,
  },
  activityTimelineRow: { flexDirection: "row", minHeight: 82 },
  activityTimelineList: { gap: 0 },
  activityTimelineRail: { width: 38, alignItems: "center" },
  activityTimelineIcon: {
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  activityTimelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: colors.border,
  },
  activityTimelineBody: { flex: 1, paddingLeft: 8, paddingBottom: 18 },
  requestList: { gap: 10 },
  requestCard: { padding: 14, gap: 11 },
  requestCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  flexNoMargin: { flex: 1 },
  requestQuantity: { color: colors.ink, fontSize: 17, fontWeight: "800" },
  requestCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  requestDetail: { gap: 14 },
  requestDetailTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" },
  backAction: { flexDirection: "row", alignItems: "center", gap: 8 },
  backActionText: { color: colors.primary, fontSize: 11, fontWeight: "700" },
  detailGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  detailItem: { minWidth: "46%", flex: 1 },
  context: {
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  contextLabel: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.7,
  },
  contextValue: { color: colors.ink, fontSize: 11, marginTop: 3 },
  fieldWrap: { gap: 7 },
  fieldLabel: {
    color: colors.inkMuted,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  field: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.ink,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    textAlignVertical: "top",
  },
  fieldLarge: { minHeight: 84 },
  success: { alignItems: "center", padding: 34, paddingBottom: 18 },
  successIcon: {
    width: 68,
    height: 68,
    borderRadius: 24,
    backgroundColor: colors.success,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  successTitle: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  successCopy: {
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 19,
    textAlign: "center",
    marginVertical: 12,
  },
  list: { paddingHorizontal: 20, paddingBottom: 14, gap: 16 },
  notification: {
    flexDirection: "row",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  itemIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  flex: { flex: 1, marginLeft: 12 },
  itemTitle: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  itemMeta: {
    color: colors.inkMuted,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 3,
  },
  time: { color: colors.inkMuted, fontSize: 8, marginTop: 5 },
  unread: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  profile: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 14,
    alignItems: "center",
    gap: 10,
  },
  profileAvatar: {
    width: 82,
    height: 82,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarText: { color: colors.white, fontSize: 25, fontWeight: "800" },
  profileName: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  profileEditButton: {
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 13,
    backgroundColor: colors.primarySoft,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginBottom: 4,
  },
  profileEditButtonText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "800",
  },
  settingsSegments: {
    flexDirection: "row",
    gap: 8,
  },
  settingsSegment: {
    flex: 1,
    minHeight: 46,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  settingsSegmentActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  settingsSegmentText: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  settingsSegmentTextActive: { color: colors.white },
  settingsHint: { color: colors.inkMuted, fontSize: 10, lineHeight: 15 },
  settingsCard: { paddingHorizontal: 14 },
  settingsRow: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  settingsRowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
  settingsRowDisabled: { opacity: 0.45 },
  settingsInfo: {
    padding: 14,
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  settingsInfoText: {
    flex: 1,
    color: colors.inkMuted,
    fontSize: 10,
    lineHeight: 16,
  },
  info: { width: "100%", flexDirection: "row", alignItems: "center" },
  infoLabel: { color: colors.inkMuted, fontSize: 9 },
  infoValue: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 3,
  },
  cash: { borderRadius: 22, padding: 20 },
  cashLabel: { color: "rgba(255,255,255,.65)", fontSize: 9, fontWeight: "800" },
  cashValue: {
    color: colors.white,
    fontSize: 32,
    fontWeight: "800",
    marginTop: 7,
  },
  cashMeta: { color: "rgba(255,255,255,.7)", fontSize: 11, marginTop: 15 },
  listHeading: {
    color: colors.inkMuted,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  card: { paddingHorizontal: 15 },
  divider: { height: 1, backgroundColor: colors.border },
  note: { color: colors.inkMuted, fontSize: 10, textAlign: "center" },
  messageScreen: { flex: 1, minHeight: 0 },
  messageList: { flex: 1 },
  messages: { paddingHorizontal: 20, paddingTop: 2, paddingBottom: 16 },
  bubble: { maxWidth: "84%", borderRadius: 17, padding: 12, marginBottom: 10 },
  incoming: {
    alignSelf: "flex-start",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  outgoing: { alignSelf: "flex-end", backgroundColor: colors.primary },
  bubbleText: { color: colors.ink, fontSize: 12, lineHeight: 18 },
  bubbleTextOutgoing: { color: colors.white },
  bubbleTime: { color: "rgba(255,255,255,.6)" },
  composer: {
    flexDirection: "row",
    gap: 8,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  messageInput: {
    flex: 1,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 13,
  },
  send: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  document: { flexDirection: "row", alignItems: "center", paddingVertical: 14 },
  taskId: { color: colors.inkMuted, fontSize: 10, fontWeight: "800" },
  taskContent: { padding: 20, paddingTop: 4, paddingBottom: 12, gap: 16 },
  pills: { flexDirection: "row", gap: 8 },
  description: { color: colors.inkMuted, fontSize: 13, lineHeight: 20 },
  progressValue: { color: colors.ink, fontSize: 26, fontWeight: "800" },
  sliderCard: {
    paddingHorizontal: 4,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  slider: { width: "100%", height: 38 },
  sliderLabels: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  sliderLabel: { color: colors.inkMuted, fontSize: 9, fontWeight: "700" },
  sliderHint: { color: colors.primary, fontSize: 9, fontWeight: "600" },
  progressForm: { padding: 20, paddingTop: 2, gap: 15, paddingBottom: 12 },
  stageGrid: { flexDirection: "row", gap: 8 },
  stageOption: {
    flex: 1,
    minHeight: 66,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 6,
  },
  stageOptionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  stageText: {
    color: colors.inkMuted,
    fontSize: 9,
    fontWeight: "700",
    textAlign: "center",
  },
  stageTextActive: { color: colors.white },
  progressHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  progressHeadingValue: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
  },
  progressHistory: { gap: 10, marginTop: 8 },
  table: {
    minWidth: 610,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    overflow: "hidden",
  },
  tableRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
  },
  tableHeader: { minHeight: 38, backgroundColor: colors.primarySoft },
  tableRowAlternate: { backgroundColor: colors.surfaceAlternate },
  tableCell: {
    color: colors.ink,
    fontSize: 10,
    lineHeight: 14,
    paddingHorizontal: 10,
  },
  tableHeadText: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  dateCell: { width: 95 },
  stageCell: { width: 115 },
  workCell: { width: 300 },
  percentCell: { width: 100, fontWeight: "800" },
  statusOptions: { gap: 8 },
  statusOption: {
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusOptionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  statusOptionText: {
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: "700",
  },
  statusOptionTextActive: { color: colors.white },
  requirementNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 12,
    borderRadius: 13,
    backgroundColor: colors.accentSoft,
  },
  requirementText: { flex: 1, color: colors.warning, fontSize: 10 },
  evidenceStages: { gap: 16 },
  evidenceStage: {
    gap: 9,
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  evidenceStageHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  evidenceStageNumber: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  evidenceStageNumberText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: "800",
  },
  evidenceStageTitle: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  evidenceStageCopy: { color: colors.inkMuted, fontSize: 9, marginTop: 2 },
  historySection: { gap: 12, marginTop: 4 },
  emptyHistory: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 20,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
  },
  emptyHistoryText: { color: colors.inkMuted, fontSize: 11 },
  historyRow: { flexDirection: "row", minHeight: 78 },
  timelineColumn: { width: 20, alignItems: "center" },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.accent,
    marginTop: 5,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: colors.border,
    marginVertical: 4,
  },
  historyBody: { flex: 1, paddingLeft: 8, paddingBottom: 16 },
  historyTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  historyProgress: { color: colors.ink, fontSize: 11, fontWeight: "800" },
  historyRemark: {
    color: colors.ink,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 7,
  },
  evidenceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  evidenceName: { flex: 1, color: colors.primary, fontSize: 9 },
  evidenceLabel: { color: colors.inkMuted, fontSize: 9, fontWeight: "700" },
  historyDate: { color: colors.inkMuted, fontSize: 8, marginTop: 6 },
  taskHistoryTable: { minWidth: 810 },
  historyDateCell: { width: 95 },
  historyStatusCell: { width: 105 },
  historyProgressCell: { width: 80, fontWeight: "800" },
  historyRemarkCell: { width: 230 },
  historyEvidenceCell: { width: 300, color: colors.primary },
});
